plugins {
    id 'java-library'
    id "edu.wpi.first.GradleRIO" version "2026.2.1"
    //id 'com.github.sherter.google-java-format' version '1.34.1'

}
dependencies {
    implementation project(':annotation')
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation wpi.java.deps.wpilib()
    implementation wpi.java.vendor.java()
}


group 'com.orangefrc'
version globalVersion
